[package]
name = "starkcash"
version = "0.1.0"
edition = "2023_10"

[dependencies]
starknet = ">=2.4.0"

[dev-dependencies]
cairo_test = "2.15.1"

[[target.starknet-contract]]
sierra = true
casm = true
